server:
  port: 8004

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes: 
        - id: neo_route
        uri: http://www.ityouknow.com
        predicates:
        - Path=/spring-cloud
#注册中心指向start    
eureka:
  instance:
    instance-id: spring-cloud-user
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://admin:wukeji@127.0.0.1:8888/eureka/
#注册中心指向end 