server:
  port: 8003

spring:
  application:
    name: spring-cloud-picture

#注册中心指向start    
eureka:
  instance:
    instance-id: spring-cloud-picture
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://admin:wukeji@localhost:8888/eureka/
#注册中心指向end

#阿里云
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAIdsPzHK3f2fAy
    access-key-secret: ooE55Ns6l3LCmwuQ0FVKGgaAiBVV6M
    default-bucket-name: wkj-local
    upload-root-url: https://wkj-local.oss-cn-beijing.aliyuncs.com/
