server:
  port: 8002

spring:
  application:
    name: spring-cloud-user
    
#注册中心指向start    
eureka:
  instance:
    instance-id: spring-cloud-user
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://admin:wukeji@127.0.0.1:8888/eureka/
#注册中心指向end

#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://127.0.0.1:3306/lmrp2?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
#      username: root
#      password: wukeji
##Mybatis配置
#mybatis:
#  #配置mapper xml文件所在的路径
#  mapper-locations: classpath:mapper/*.xml
#  #配置映射类所在的包名
#  type-aliases-package: com.mapper      