server:
  port: 8002

spring:
  application:
    name: spring-cloud-user

#注册中心指向start    
eureka:
  instance:
    instance-id: spring-cloud-user
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://admin:wukeji@127.0.0.1:8888/eureka/
#注册中心指向end