server:
  port: 8002

spring:
  application:
    name: spring-cloud-user
spring:
  datasource:
    user-server:
      url: jdbc:mysql://127.0.0.1:3306/lmrp?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: root
      password: wukeji
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    user-server-separate:
      url: jdbc:mysql://127.0.0.1:3306/lmrp2?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
      username: root
      password: wukeji
      driver-class-name: com.mysql.jdbc.Driver
      max-idle: 10
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

#注册中心指向start    
eureka:
  instance:
    instance-id: spring-cloud-user
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://admin:wukeji@127.0.0.1:8888/eureka/
#注册中心指向end